data_path: data/ard100_roi640.yaml
conf_file: configs/et_yolov6s_ard100_roi640_nwd.py
img_size: 640
rect: false
batch_size: 32
epochs: 400
workers: 8
device: 0,1
eval_interval: 5
eval_final_only: false
heavy_eval_range: 50
check_images: false
check_labels: false
output_dir: runs/train
name: et_yolov6s_ard100_roi640_nwd
dist_url: env://
gpu_count: 0
local_rank: 0
resume: false
write_trainbatch_tb: false
stop_aug_last_n_epoch: 15
save_ckpt_on_last_n_epoch: -1
distill: false
distill_feat: false
quant: false
calib: false
teacher_model_path: null
temperature: 20
fuse_ab: false
bs_per_gpu: 32
specific_shape: false
height: null
width: null
cache_ram: false
rank: 0
world_size: 2
save_dir: runs/train/et_yolov6s_ard100_roi640_nwd
